### PR TITLE
Fix escaping of integer indexes with multiple backslashes

### LINKED ISSUE #1285: Escaping backslashes in nested json keys
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

Run ` http httpbin.org/post 'foo[\\8]=bar' --offline`

## Current result

```bash
POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 21
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/3.0.0

{
    "foo": {
        "8": "bar"
    }
}
```

## Expected result

Double a backslash anywhere should turn it into a literal backslash.

```bash
POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 21
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/3.0.0

{
    "foo": {
        "\\8": "bar"
    }
}
```

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
http httpbin.org/post 'foo[\\8]=bar' --offline --debug
HTTPie 3.0.0
Requests 2.22.0
Pygments 2.7.2
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]
/usr/bin/python3
Linux 5.10.81.1-microsoft-standard-WSL2

<Environment {'as_silent': <function Environment.as_silent at 0x7fc8d8712550>,
 'colors': 256,
 'config': {'default_options': []},
 'config_dir': PosixPath('/home/ducaale/.httpie'),
 'devnull': <property object at 0x7fc8d8aea950>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7fc8d87125e0>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

<PluginManager {'adapters': [],
 'auth': [<class 'httpie.plugins.builtin.BasicAuthPlugin'>,
          <class 'httpie.plugins.builtin.DigestAuthPlugin'>,
          <class 'httpie.plugins.builtin.BearerAuthPlugin'>],
 'converters': [],
 'formatters': [<class 'httpie.output.formatters.headers.HeadersFormatter'>,
                <class 'httpie.output.formatters.json.JSONFormatter'>,
                <class 'httpie.output.formatters.xml.XMLFormatter'>,
                <class 'httpie.output.formatters.colors.ColorFormatter'>]}>

>>> requests.request(**{'auth': None,
 'data': b'{"foo": {"8": "bar"}}',
 'headers': <HTTPHeadersDict('User-Agent': b'HTTPie/3.0.0', 'Accept': b'application/json, */*;q=0.5', 'Content-Type': b'application/json')>,
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x7fc8d83727b0>,
 'url': 'http://httpbin.org/post'})

POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 21
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/3.0.0

{
    "foo": {
        "8": "bar"
    }
}
```

## Additional information, screenshots, or code examples

N/A

### PR DESCRIPTION
**Pull request by isidentical**
Resolves #1285

### CODE REVIEW

**Comment by jakubroztocil** [comment]
Great fix! I think this deserver a mention in `CHANGELOG.md`.

**Comment by isidentical** [comment]
@jakubroztocil I think we already do (if I am not missing anything).

**Comment by isidentical** [comment]
https://github.com/httpie/httpie/blob/master/CHANGELOG.md

**Comment by jakubroztocil** [comment]
Sorry, yes, we do!

**Pull request merged**
