### PR TITLE
Re-design nested JSON spec

### PR DESCRIPTION
**Pull request by isidentical**

### CODE REVIEW

**Review by jakubroztocil — CHANGES_REQUESTED** [review]
Great stuff 🙌🏻  I’d just introduce some constants for things like `[`, `]`, `\\`, `append`, etc. 

I’m polishing the docs in the meantime, and might tweak the error message a bit — will push the changes to this PR.

**Comment by isidentical** [comment]
Sure, waiting for you. As you have probably noticed, for the constants `[`/`]` etc. we already use tokens whenever we can, so their usage is pretty limited. And I think `path.kind` can be an enum, but not a really high priority.

**Comment by jakubroztocil** [comment]
> Sure, waiting for you. As you have probably noticed, for the constants `[`/`]` etc. we already use tokens whenever we can, so their usage is pretty limited. And I think `path.kind` can be an enum, but not a really high priority.

My point is that there’s a lot of unnamed string references to strings with a special meaning. The code will be easier to understand and navigate if we consistently use named constants/enums.

**Comment by isidentical** [comment]
> My point is that there’s a lot of unnamed string references to strings with a special meaning. The code will be easier to understand and navigate if we consistently use named constants/enums.

I'll try to enumerize the `kind`s (`append`/`index`/`key`/`set`).

**Pull request merged**
