### PR TITLE
Updated fish shell completions

### PR DESCRIPTION
**Pull request by exploide**
Just brought the completions for fish shell up to date.

### CODE REVIEW

**Comment by jakubroztocil** [comment]
Thanks, @exploide! 🐟🐚 🎉

**Comment by hroncok** [comment]
I was jst installing those in the Fedora package and was wondering: Will this work for `https` command?

**Comment by exploide** [comment]
> I was just installing those in the Fedora package

Hey @hroncok thanks for addressing my bugzilla issue. :) Just left positive karma on bodhi for the F34 update.

As of now, I was not even aware that there is an `https` command (that is the same as `http`).

> Will this work for https command?

Not directly. We would need an additional completion file `https.fish` that just contains `complete -c https -w http`. This means that completions for `https` are wrapping those of `http`.

How should be proceed? Will you create that file as part of the build step? Or we can ask @jakubroztocil if we can add that additional file to the repository.

**Comment by hroncok** [comment]
Having that wrapper here would make more sense to me, that way, others can use it as well.
Is something similar working for Bash?

**Pull request merged**
