### PR TITLE
Add initial benchmarking infrastructure

### PR DESCRIPTION
**Pull request by isidentical**

### CODE REVIEW

**Comment by isidentical** [comment]
Here is a real example: https://github.com/httpie/httpie/pull/1233#issuecomment-987864883

**Review by jakubroztocil — CHANGES_REQUESTED** [review]
Good stuff.

- [ ] it would be good to explain the system (including the labeling) —perhaps add it to `CONTRIBUTING.md` in addition to the PR’s description
- [ ] the output should be super easy to skim: currently, it’s not super clear what each test does and it takes some effort to understand  what the impact of the PR is
- [ ] here we could use some more docs in the code as well (I’m generally for self-explanatory rather than commented code, but here they’d add value)

**Comment by isidentical** [comment]
@jakubroztocil how about this?
https://github.com/httpie/httpie/pull/1233#issuecomment-989733988
image

**Comment by isidentical** [comment]
Another example;
image

**Pull request merged**
