### PR TITLE
Add a workflow to check documentations

### PR DESCRIPTION
**Pull request by BoboTiG**
The new tool can be installed using that command:
```bash
$ gem install mdl
```
Then use it like:
```bash
$ make doc-check
```

### CODE REVIEW

**Comment by BoboTiG** [comment]
In case of error, here is a output sample:
```bash
.github/ISSUE_TEMPLATE/bug_report.md:23: MD012 Multiple consecutive blank lines
.github/ISSUE_TEMPLATE/bug_report.md:26: MD012 Multiple consecutive blank lines
.github/ISSUE_TEMPLATE/bug_report.md:29: MD012 Multiple consecutive blank lines
.github/ISSUE_TEMPLATE/bug_report.md:39: MD012 Multiple consecutive blank lines
.github/ISSUE_TEMPLATE/bug_report.md:10: MD036 Emphasis used instead of a header
.github/ISSUE_TEMPLATE/bug_report.md:30: MD036 Emphasis used instead of a header
.github/ISSUE_TEMPLATE/bug_report.md:34: MD040 Fenced code blocks should have a language specified
.github/ISSUE_TEMPLATE/feature_request.md:17: MD012 Multiple consecutive blank lines
.github/ISSUE_TEMPLATE/feature_request.md:22: MD012 Multiple consecutive blank lines
.github/ISSUE_TEMPLATE/feature_request.md:9: MD036 Emphasis used instead of a header

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
```

**Comment by BoboTiG** [comment]
GitHub templates are a mess so they are not checked at all for now.
If we wanted to handle the, the command in the `Makefile` would become:
```diff
- 	mdl --style docs/linter/mdl-styles.rb *.md docs/*.md tests/*.md
+ 	mdl --git-recurse --style docs/linter/mdl-styles.rb .
```

**Comment by Amirjokr** [comment]
#1202

**Comment by Amirjokr** [comment]
#1095 many app stor google play erorr

**Pull request merged**
