### PR TITLE
Use relative imports

### PR DESCRIPTION
**Pull request by BoboTiG**
This is a first start, I would like to clean-up the source code to ease future contributions (and why not run a code formatter later, after discussion).

The only place where absolute imports are needed is in `__main__.py` because I know that some code freezers may have issues with that (for the future though).

### CODE REVIEW

**Comment by jakubroztocil** [comment]
Thank you, @BoboTiG 🥧🥧🥧

**Comment by hroncok** [comment]
Beware, this now installs:

```
   /usr/lib/python3.9/site-packages/tests/__init__.py
   /usr/lib/python3.9/site-packages/tests/__pycache__/...
   /usr/lib/python3.9/site-packages/tests/conftest.py
   /usr/lib/python3.9/site-packages/tests/fixtures/__init__.py
   /usr/lib/python3.9/site-packages/tests/fixtures/__pycache__/...
   /usr/lib/python3.9/site-packages/tests/test_auth.py
   /usr/lib/python3.9/site-packages/tests/test_auth_plugins.py
   /usr/lib/python3.9/site-packages/tests/test_binary.py
   /usr/lib/python3.9/site-packages/tests/test_cli.py
   /usr/lib/python3.9/site-packages/tests/test_compress.py
   /usr/lib/python3.9/site-packages/tests/test_config.py
   /usr/lib/python3.9/site-packages/tests/test_defaults.py
   /usr/lib/python3.9/site-packages/tests/test_docs.py
   /usr/lib/python3.9/site-packages/tests/test_downloads.py
   /usr/lib/python3.9/site-packages/tests/test_errors.py
   /usr/lib/python3.9/site-packages/tests/test_exit_status.py
   /usr/lib/python3.9/site-packages/tests/test_httpie.py
   /usr/lib/python3.9/site-packages/tests/test_offline.py
   /usr/lib/python3.9/site-packages/tests/test_output.py
   /usr/lib/python3.9/site-packages/tests/test_redirects.py
   /usr/lib/python3.9/site-packages/tests/test_regressions.py
   /usr/lib/python3.9/site-packages/tests/test_sessions.py
   /usr/lib/python3.9/site-packages/tests/test_ssl.py
   /usr/lib/python3.9/site-packages/tests/test_stream.py
   /usr/lib/python3.9/site-packages/tests/test_tokens.py
   /usr/lib/python3.9/site-packages/tests/test_unicode.py
   /usr/lib/python3.9/site-packages/tests/test_uploads.py
   /usr/lib/python3.9/site-packages/tests/test_windows.py
   /usr/lib/python3.9/site-packages/tests/utils/__init__.py
   /usr/lib/python3.9/site-packages/tests/utils/__pycache__/...
   /usr/lib/python3.9/site-packages/tests/utils/matching/__init__.py
   /usr/lib/python3.9/site-packages/tests/utils/matching/__pycache__/...
   /usr/lib/python3.9/site-packages/tests/utils/matching/parsing.py
   /usr/lib/python3.9/site-packages/tests/utils/matching/test_matching.py
```

Because `find_packages()` in `setup.py` finds the `tests` package (due to added `tests/__init__.py`).

**Comment by BoboTiG** [comment]
OK I will revert those changes, thanks for the catch.

**Comment by hroncok** [comment]
Alternatively, don't use `find_packages()`. We always only want to install the `httpie` package.

**Comment by BoboTiG** [comment]
Will be tackled with #1087.

**Pull request merged**
