### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by henryhu712**
fix typo

### CODE REVIEW

**Review by BoboTiG — APPROVED** [review]

**Comment by BoboTiG** [comment]
Thanks :pie:

**Comment by jakubroztocil** [comment]
That wasn't a typo. It intentionally uses the `https` version of the command. Now it no longer does what it's supposed to. Please revert @BoboTiG

**Comment by jakubroztocil** [comment]
image

**Comment by BoboTiG** [comment]
:+1:

**Pull request merged**
