### PR TITLE
Prevent packaging of test files

### PR DESCRIPTION
**Pull request by BoboTiG**
cc @hroncok

### CODE REVIEW

**Comment by hroncok** [comment]
This should fix the problem. To verify, I've included this commit in https://github.com/httpie/httpie/pull/1086

**Comment by hroncok** [comment]
Oh, no. It does not include subpackages :(

**Comment by BoboTiG** [comment]
Yup I just fixed it now :)

**Comment by hroncok** [comment]
I'd use `setuptools.find_packages(include=['httpie*'])` to avoid a hardcoded list.

**Comment by jakubroztocil** [comment]
Thanks @BoboTiG & @hroncok! 🎉🥧

**Pull request merged**
