### PR TITLE
Introduce CurliPie to convert from cURL to HTTPie

### PR DESCRIPTION
**Pull request by hongquan**

### CODE REVIEW

**Comment by CyberMew** [comment]
curl -i --data-binary "@build/veracode.bca" -H "Content-Type: binary/octet-stream" -u "$USER:$PASS" "https://analysiscenter.veracode.com/api/5.0/uploadlargefile.do?app_id=$VERACODE_APP_ID&filename=file.bca" --cacert ~/Desktop/cert.pem 

^ the above broke it

**Comment by hongquan** [comment]
Thanks, @CyberMew

**Comment by hongquan** [comment]
@CyberMew I fixed this case.

**Comment by jakubroztocil** [comment]
Thanks @hongquan! 🥳

**Pull request merged**
